### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/red#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (sorry, we are waaaay behind on getting
documentation updated).
https://github.com/exercism/legacy-docs/blob/main/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the `#maintaining-***` channels and `#maintainers` private channel in the *exercism-team* Slack workspace.

Please ask if you have any questions or if anything is confusing!

## Checklist

- [x] Fill `config.json` data with task's language info
- [x] Update `config/maintainers.json` with maintainers' data
- [x] Include most important info in `README.md`
- [x] Write fist excercise, most probably *Hello, World*
- [x] Test it (test the tests? ;) )
- [x] Track/language documentation – *docs* folder
- [x] Which other languages from Exercism to follow and use as an example / inspiration? (#3)
- [x] ~~Mentoring sessions transcripts as an example for future mentors.~~
- [x] Create a list of exercises we want the most to include in Red track
- [x] Decide on testing (#5)
- [x] (optionally) create [test generator](https://github.com/exercism/problem-specifications)
- [x] `[v3]` airdrop tasks (#20)
- [x] `[v3]` airdrop commits (#21)

**Comment by loziniak** [comment]
Launched an double-checked!
